### ISSUE TITLE
firewalled-replit.com docs updates

### ISSUE THREAD

**Issue by qirtaiba** [replit/replit-docs-2#1]
Please merge these documentation changes for the launch of firewalled-replit.com, projected for Tuesday May 31: 

https://replit.com/@qirtaiba/replit-docs-2

**Comment by Bardia95** [comment]
Hey can you actually make a GitHub pull request to this repo with the changes?

**Comment by qirtaiba** [comment]
OK, should be done. At first I tried to fork your repl and make the changes there, but I couldn't find a way to push it back to github. So I started over and just made a fork on Github instead. If there is some documentation about the process other than your message in Slack,  or if I did something wrong, please let me know.

**Comment by Bardia95** [comment]
Sorry, I should have rolled out the docs with more clear instructions! I just made a step-by-step guide and will post internally.

You're good!

**Comment by Bardia95** [comment]
Sorry, I should have rolled out the docs with more clear instructions! I just made a step-by-step guide and will post internally.

You're good!
